### PR TITLE
Setup cocoapods for dependancy management

### PR DESCRIPTION
**Pull request by daveingle**
I've switched the example to use pods instead of submodules.
Also I tweeked the folder structure.

The .gitignore file via this gist: https://gist.github.com/adamgit/3786883

### CODE REVIEW

**Comment by kylebrowning** [comment]
The Drupal iOS SDK also has a pod now. Mind updating this pull request?

**Comment by daveingle** [comment]
Will do
-—-
David Ingle 778.881.4847

**Comment by daveingle** [comment]
Was going to circle back to this tonight, have you pushed the 2.0.3 tag? Cocoapods doesn't seem to be pulling the code from your repo.

**Comment by kylebrowning** [comment]
I just re-published the tag.

**Comment by daveingle** [comment]
Interesting, all I get in the drupal-ios-sdk directory after a 'pod install' is LICENSE and README.md

Completely willing to admit this could be a problem on my end. Suggestions?

**Comment by kylebrowning** [comment]
It might be something with my pod spec :/

**Comment by daveingle** [comment]
Maybe you need to add s.source_files to the spec?

**Comment by kylebrowning** [comment]
https://github.com/CocoaPods/Specs/pull/2863

**Comment by daveingle** [comment]
That did the trick, I'll update the pull request after work tonight.

**Pull request closed without merging**
